[env:m5stick-c-plus2]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
    m5stack/M5StickCPlus2@^1.0.2
    bblanchon/ArduinoJson@^6.21.4
    https://github.com/tzapu/WiFiManager.git#v2.0.17
lib_ignore =
    DFRobot_GP8XXX
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=0
